# -*- coding: utf-8 -*-
"""Smart Manufacturing IoT-Cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u4NXwWEwRZARNY776MtJh0eAdVuYugd5
"""
# ==========================================
# PREPROCESSING DATA SMART MANUFACTURING
# ==========================================
# Script preprocessing untuk proyek
# Smart Manufacturing IoT-Cloud Monitoring
# Bagian: Data Engineer
#
# Tahapan:
# - Load dataset
# - Preprocessing data
# - Feature engineering
# - Encoding data kategorikal
# - Penyimpanan dataset bersih

# Import library dasar
import pandas as pd
import numpy as np

# Import library untuk visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

# Mengatur tampilan grafik
sns.set_style("whitegrid")

# Membaca dataset
df = pd.read_csv('smart_manufacturing_data_10000.csv')

# Menampilkan informasi bahwa dataset berhasil dibaca
print("Dataset berhasil dibaca!")

df.head()

df.shape

# Menampilkan seluruh nama kolom
print("Daftar kolom:")
for i, column in enumerate(df.columns, start=1):
    print(i, ".", column)

# Informasi dataset
df.info()

# Mengecek jumlah missing value pada setiap kolom
missing_values = df.isnull().sum()

print("Jumlah missing value:")
print(missing_values)

# Mengecek jumlah missing value pada setiap kolom
missing_values = df.isnull().sum()

print("Jumlah missing value:")
print(missing_values)

# Menampilkan statistik deskriptif
df.describe()

# Melihat jumlah masing-masing jenis kegagalan
df['failure_type'].value_counts()

# Melihat jumlah masing-masing status mesin
df['machine_status'].value_counts()

# Melihat distribusi data anomali
df['anomaly_flag'].value_counts()

# Membuat histogram temperature
plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x='temperature',
    bins=30,
    kde=True
)

plt.title('Distribusi Temperature')
plt.xlabel('Temperature')
plt.ylabel('Jumlah Data')

plt.show()

# Membuat histogram vibration
plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x='vibration',
    bins=30,
    kde=True
)

plt.title('Distribusi Vibration')
plt.xlabel('Vibration')
plt.ylabel('Jumlah Data')

plt.show()

# Membuat histogram energy consumption
plt.figure(figsize=(8, 5))

sns.histplot(
    data=df,
    x='energy_consumption',
    bins=30,
    kde=True
)

plt.title('Distribusi Energy Consumption')
plt.xlabel('Energy Consumption')
plt.ylabel('Jumlah Data')

plt.show()

# Membuat boxplot temperature
plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x='temperature'
)

plt.title('Boxplot Temperature')
plt.xlabel('Temperature')

plt.show()

# Membuat boxplot vibration
plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x='vibration'
)

plt.title('Boxplot Vibration')
plt.xlabel('Vibration')

plt.show()

# Membuat boxplot humidity
plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x='humidity'
)

plt.title('Boxplot Humidity')
plt.xlabel('Humidity')

plt.show()

# Membuat boxplot pressure
plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x='pressure'
)

plt.title('Boxplot Pressure')
plt.xlabel('Pressure')

plt.show()

# Membuat boxplot energy consumption
plt.figure(figsize=(8, 5))

sns.boxplot(
    data=df,
    x='energy_consumption'
)

plt.title('Boxplot Energy Consumption')
plt.xlabel('Energy Consumption')

plt.show()

# Menghitung korelasi antar variabel numerik
correlation = df.select_dtypes(include=np.number).corr()

# Menampilkan tabel korelasi
correlation

# Membuat heatmap korelasi
plt.figure(figsize=(12, 8))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Heatmap')

plt.show()

# Menghitung jumlah masing-masing kelas anomaly
print(df['anomaly_flag'].value_counts())

# Membuat grafik distribusi anomaly
plt.figure(figsize=(6, 4))

sns.countplot(
    data=df,
    x='anomaly_flag'
)

plt.title('Distribusi Anomaly Flag')
plt.xlabel('Anomaly Flag')
plt.ylabel('Jumlah Data')

plt.show()

# Melihat jumlah masing-masing kelas maintenance
print(df['maintenance_required'].value_counts())

# Membuat grafik distribusi maintenance
plt.figure(figsize=(6, 4))

sns.countplot(
    data=df,
    x='maintenance_required'
)

plt.title('Distribusi Maintenance Required')
plt.xlabel('Maintenance Required')
plt.ylabel('Jumlah Data')

plt.show()

# Membuat salinan dataset untuk preprocessing
df_clean = df.copy()

# Melihat ukuran dataset
print("Ukuran dataset:", df_clean.shape)

# Mengubah kolom timestamp menjadi datetime
df_clean['timestamp'] = pd.to_datetime(df_clean['timestamp'])

# Melihat tipe data timestamp
print(df_clean['timestamp'].dtype)

# Mengambil tahun dari timestamp
df_clean['year'] = df_clean['timestamp'].dt.year

# Melihat hasilnya
df_clean[['timestamp', 'year']].head()

# Mengambil bulan dari timestamp
df_clean['month'] = df_clean['timestamp'].dt.month

# Melihat hasilnya
df_clean[['timestamp', 'month']].head()

# Mengambil hari dari timestamp
df_clean['day'] = df_clean['timestamp'].dt.day

# Melihat hasilnya
df_clean[['timestamp', 'day']].head()

# Mengambil jam dari timestamp
df_clean['hour'] = df_clean['timestamp'].dt.hour

# Melihat hasilnya
df_clean[['timestamp', 'hour']].head()

# Mengambil hari dalam minggu
df_clean['day_of_week'] = df_clean['timestamp'].dt.dayofweek

# Melihat hasilnya
df_clean[['timestamp', 'day_of_week']].head()

# Melihat kategori failure type
print(df_clean['failure_type'].unique())

# Melakukan one-hot encoding pada failure_type
df_clean = pd.get_dummies(
    df_clean,
    columns=['failure_type'],
    prefix='failure'
)

# Melihat 5 data pertama
df_clean.head()

# Melihat seluruh kolom setelah preprocessing
print("Jumlah kolom:", len(df_clean.columns))
print("\nNama kolom:")
print(df_clean.columns.tolist())

# Melihat informasi dataset setelah preprocessing
df_clean.info()

# Menghapus kolom timestamp karena informasinya sudah
# diubah menjadi fitur waktu
df_clean = df_clean.drop(columns=['timestamp'])

# Melihat ukuran dataset
print("Ukuran dataset setelah menghapus timestamp:", df_clean.shape)

# Melihat 5 data pertama setelah preprocessing
df_clean.head()

# Mengecek kembali missing value
print("Missing value setelah preprocessing:")
print(df_clean.isnull().sum())

# Mengecek kembali data duplikat
print("Jumlah duplikat:", df_clean.duplicated().sum())

# Melihat 5 data pertama setelah preprocessing
df_clean.head()

# Melihat ukuran dataset setelah preprocessing
print("Jumlah baris :", df_clean.shape[0])
print("Jumlah kolom :", df_clean.shape[1])

# Melihat tipe data setiap kolom
df_clean.info()

# Mengecek missing value pada dataset akhir
missing_final = df_clean.isnull().sum().sum()

print("Total missing value:", missing_final)

# Mengecek data duplikat pada dataset akhir
duplicate_final = df_clean.duplicated().sum()

print("Total data duplikat:", duplicate_final)

# Menyimpan dataset hasil preprocessing dan feature engineering
output_file = 'smart_manufacturing_clean.csv'

df_clean.to_csv(output_file, index=False)

print("Dataset bersih berhasil disimpan!")
print("Nama file:", output_file)

import os

# Mengecek apakah file dataset bersih sudah tersedia
if os.path.exists('smart_manufacturing_clean.csv'):
    print("File berhasil dibuat ✅")
else:
    print("File belum ditemukan ❌")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile preprocessing.py
# 
# import pandas as pd
# 
# 
# # ==========================================
# # 1. LOAD DATASET
# # ==========================================
# 
# input_file = 'smart_manufacturing_data_10000.csv'
# 
# df = pd.read_csv(input_file)
# 
# 
# # ==========================================
# # 2. PREPROCESSING TIMESTAMP
# # ==========================================
# 
# df['timestamp'] = pd.to_datetime(df['timestamp'])
# 
# 
# # ==========================================
# # 3. FEATURE ENGINEERING
# # ==========================================
# 
# df['year'] = df['timestamp'].dt.year
# df['month'] = df['timestamp'].dt.month
# df['day'] = df['timestamp'].dt.day
# df['hour'] = df['timestamp'].dt.hour
# df['day_of_week'] = df['timestamp'].dt.dayofweek
# 
# 
# # ==========================================
# # 4. ENCODING DATA KATEGORIKAL
# # ==========================================
# 
# df = pd.get_dummies(
#     df,
#     columns=['failure_type'],
#     prefix='failure'
# )
# 
# 
# # ==========================================
# # 5. MENGHAPUS TIMESTAMP
# # ==========================================
# 
# df = df.drop(columns=['timestamp'])
# 
# 
# # ==========================================
# # 6. CEK HASIL
# # ==========================================
# 
# print("Preprocessing selesai.")
# print("Ukuran dataset:", df.shape)
# print("Missing value:", df.isnull().sum().sum())
# print("Duplikat:", df.duplicated().sum())
# 
# 
# # ==========================================
# # 7. SIMPAN DATASET BERSIH
# # ==========================================
# 
# output_file = 'smart_manufacturing_clean.csv'
# 
# df.to_csv(output_file, index=False)
# 
# print("Dataset bersih:", output_file)

!python preprocessing.py

import os

print("File yang tersedia:")
for file in os.listdir():
    print(file)

# Membaca kembali dataset bersih
df_final = pd.read_csv('smart_manufacturing_clean.csv')

# Menampilkan 5 data pertama
df_final.head()

